openapi: 3.0.0
info:
  title: CleanTable Customer API
  description: An API intended for use by the mobile API.
  version: "1.0"

servers:
  - url: https://comp2003-f-api.azurewebsites.net/api/
    description: Cloud API hosting

tags:
- name: "Venues"
  description: "Venues of the system"
  
paths:
  /venues/search/:
    get:
      tags:
      - Venues
      summary: Returns a compressed list of venues
      description: Gets a compressed list of venues designed to be displayed on a search page - only necessary information for this purpose is given.
      parameters:
        - in: query
          name: searchString
          required: true
          schema:
            type: string
          description: A venue name, city name, or postcode
      responses:
        "200":
          description: A JSON array of venue information
          content: 
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    city:
                      type: string
                    postcode:
                      type: string